urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django_authopenid.urls import urlpatterns as authopenid_urlpatterns
from registration.forms import RegistrationFormUniqueEmail

from djangobb_forum import settings as forum_settings

from mezzanine.core.views import direct_to_template

for i, rurl in enumerate(authopenid_urlpatterns):
    if rurl.name == 'registration_register':
        authopenid_urlpatterns[i].default_args.update({'form_class': RegistrationFormUniqueEmail})
        break

admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns("",

    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),
)

# PM Extension
if (forum_settings.PM_SUPPORT):
    urlpatterns += patterns('',
        (r'^forums/pm/', include('django_messages.urls')),
   )

urlpatterns += patterns("",

    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),
    #url("^blog/feeds/(?P<format>.*)/$", direct_to_template, {"template": "index.html"}, name="custom_blog_post_feed"),
    url(r'^projects/', include('projects.urls')),
    url(r'^videos/', include('videos.urls')),
    url(r'^profiles/', include("gameprofiles.urls")),
    # Overrides to fix password reset URLs in django_authopenid.
    url(r'^forums/account/password/reset/$', auth_views.password_reset,  name='password_reset'),
    url(r'^forums/account/password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^forums/account/password/reset/complete/$',
        auth_views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^forums/account/password/reset/done/$',
        auth_views.password_reset_done,
        name='password_reset_done'),
    # Apps
    url(r'^forums/account/', include('django_authopenid.urls')),
    url(r'^forums/', include('djangobb_forum.urls', namespace='djangobb')),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    # url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

videos/urls.py
from django.conf.urls import patterns, url
from .views import (IndexView, VideoDetailView, CategoryView,
    AjaxAdjacentView)

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view (), name='videos_index'),
    url(r'^category/(?P<slug>[\w-]+)/$', CategoryView.as_view (), name='videos_category'),
    url(r'^(?P<slug>[\w-]+)/$', VideoDetailView.as_view (), name="videos_detail"),
    url(r'^adjacent/(?P<cat_slug>[\w-]+)/(?P<id>\d+)/page/(?P<page>\d+)/$', AjaxAdjacentView.as_view (), name="videos_adjacent"),
)
 

videos/models.py
import re
import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.template.loader import render_to_string

from mezzanine.core.fields import FileField
from mezzanine.pages.models import Page
from mezzanine.core.models import Displayable, RichText, Slugged
from mezzanine.utils.models import AdminThumbMixin, upload_to

video_id_re = re.compile (r"http://(?:www\.)?youtube\.com/watch\?v=(\S+)(&)?.*")
blip_id_re = re.compile (r"http://(?:www\.)?blip.tv/\S+/.*-(\d+)")

class VideoCategory(Slugged):
    summary = models.CharField(max_length=200)
    description = models.TextField()

    class Meta(object):
        verbose_name_plural = "Video Categories"

    @models.permalink
    def get_absolute_url(self):
        return ("videos_category", (), {"slug": self.slug})


class Video(Displayable, RichText, AdminThumbMixin):
    featured_image = FileField(verbose_name=_("Featured Image"),
        upload_to=upload_to("videos.Video.featured_image", "uploads/video_images/%Y%m"),
        format="Image", max_length=255)#, null=True, blank=True)
    category = models.ForeignKey(VideoCategory)
    video_url = models.URLField(verbose_name=_("Video URL"),
        max_length=256)
    allow_comments = models.BooleanField(verbose_name=_("Allow comments"),
        default=True)

    admin_thumb_field = "featured_image"

    class Meta(object):
        ordering = ("-publish_date",)

    @models.permalink
    def get_absolute_url(self):
        return ('videos_detail', (), {'slug': self.slug})

    def meta_embed_url(self):
	embed_url = ""
	match = video_id_re.match (self.video_url)
	if match:
	    embed_url = "http://www.youtube.com/v/{0}?version=3&autohide=1"
	    embed_url = embed_url.format(match.group(1))

	return embed_url

    def embed_code(self):
        template = ""
        match = video_id_re.match (self.video_url)
        if match:
            template = "videos/youtube_embed.html"
            return render_to_string (template,
                {"video": self, "alias": match.group (1)})

        match = blip_id_re.match (self.video_url)
        if match:
            template = "videos/blip_embed.html"
            return render_to_string (template,
                {"video": self,
                 "alias": "http://blip.tv/rss/flash/{0}".format (match.group (1)),
                })

        return ""

    def next_video(self):
        next = None
        try:
            next = self.get_next_by_publish_date ()
        except self.__class__.DoesNotExist:
            return None

        return next

    def previous_video(self):
        previous = None
        try:
            previous = self.get_previous_by_publish_date ()
        except self.__class__.DoesNotExist:
            return None

        return previous


Video._meta.get_field("publish_date").db_index = True
Video._meta.get_field("slug").db_index = True

videos/forms.py
import re
import logging
from django import forms
from .models import Video

logger = logging.getLogger ("videos.forms") 

class VideoOptions (forms.Form):
    autoplay = forms.BooleanField (initial=False)

videos/views.py
import logging
import time
from django.views.generic import (TemplateView, ListView, DetailView,
    FormView, CreateView)
from django.shortcuts import get_object_or_404

from mezzanine.utils.views import paginate

from asylum_custom.views import CustomMezListView

from .models import Video, VideoCategory
from .forms import VideoOptions
from .conf import settings

logger = logging.getLogger ("videos.views")

class IndexView (CustomMezListView):
    model = Video
    template_name = "videos/index.html"
    ajax_template_name = "videos/list_display.html"
    paginate_by = settings.PAGINATE_BY
    max_paging_links = 10

    def get_template_names (self):
        if self.request.is_ajax ():
            return [self.ajax_template_name]

        return super (IndexView, self).get_template_names ()

    def get_context_data (self, **kwargs):
        context = super (IndexView, self).get_context_data (**kwargs)
        context["category_list"] =  VideoCategory.objects.all ().order_by ("title")
        return context


class VideoDetailView (DetailView):
    model = Video
    template_name = "videos/detail.html"

    def get_context_data (self, **kwargs):
        context = super (VideoDetailView, self).get_context_data (**kwargs)
        form = VideoOptions ()
        if self.request.COOKIES.get ("autoplay", None):
            form = VideoOptions (self.request.COOKIES)
            # If form is not valid, reset form
            if not form.is_valid ():
                form = VideoOptions ()

        context["video_options"] = form

        if context.get ("video", None):
            context["next_video"] = context["video"].next_video ()
            context["previous_video"] = context["video"].previous_video ()
            context["editable_obj"] = context["video"]

        return context


class AjaxAdjacentView (ListView):
    model = Video
    template_name="videos/adjacent_list.html"
    paginate_by = settings.ADJACENT_PAGINATE_BY

    def get_queryset (self):
        return Video.objects.filter (category__slug=self.kwargs["cat_slug"])

    def get_context_data (self, **kwargs):
        context = super (AjaxAdjacentView, self).get_context_data (**kwargs)
        context["active_video"] = get_object_or_404 (Video, id=self.kwargs["id"])
        return context


class CategoryView (IndexView):
    template_name = "videos/category.html"

    def get_queryset (self):
        return Video.objects.filter (category__slug=self.kwargs["slug"])

    def get_context_data (self, **kwargs):
        context = super (CategoryView, self).get_context_data (**kwargs)
        context["category"] = get_object_or_404 (VideoCategory,
            slug=self.kwargs["slug"])
        return context

videos/templates/videos/adjacent_list.html
{% load mezzanine_tags %}

<div id="video-list-container" class="clearfix">
    <div class="loading">
       <img src="{{ STATIC_URL }}img/ajax-loader.gif" alt="loading icon" />
    </div>

    <ul>
{% if page_obj.has_previous %}
        <li class="previous row">
            <a href="{% url "videos_adjacent" active_video.category.slug active_video.id page_obj.previous_page_number %}" class="btn btn-primary paginate previous span3"><i class="icon-arrow-left"></i> Previous</a>
        </li>
{% endif %}
{% for video in video_list %}
        <li class="adjacent_video clearfix row">
	    <a class="alignleft video-thumbnail-link span2" href="{{ video.get_absolute_url }}" title="{{ video.title }}">
		{% if video.featured_image %}
		    <img src="{{ MEDIA_URL }}{% thumbnail video.featured_image 120 90 %}" alt="{{ video.title }}" class="{% if video.get_absolute_url == active_video.get_absolute_url %}block-dark{% else %}thumbnail{% endif %}" />
		{% else %}
		    <img src="{{ STATIC_URL }}img/default_video_120x90.png" alt="{{ video.title }}" />
		{% endif %}
	    </a>

	    <div class="video-title span1">
	       <h5><a href="{{ video.get_absolute_url }}" title="{{ video.title }}">{{ video.title }}</a></h5>
	    </div>
	</li>
{% endfor %}
{% if page_obj.has_next %}
        <li class="next row">
            <a href="{% url "videos_adjacent" active_video.category.slug active_video.id page_obj.next_page_number %}" class="btn btn-primary paginate next span3">Next <i class="icon-arrow-right"></i></a>
        </li>
{% endif %}
    </ul>
</div>

videos/templates/videos/base.html
{% extends "base.html" %}
{% load mezzanine_tags i18n keyword_tags %}

{% block extra_css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}videos/css/videos.css" type="text/css" />
{% endblock %}

{% comment %}{% block meta_description %}{% spaceless %}
{% if page.get_absolute_url == request.path %}
{% metablock %}
{{ page.description }}
{% endmetablock %}
{% endif %}
{% endspaceless %}{% endblock meta_description %}


{% block meta_keywords %}{% spaceless %}
{% if page.get_absolute_url == request.path %}
{% metablock %}
{% keywords_for page as keywords %}
{% for keyword in keywords %}
    {% if not forloop.first %}, {% endif %}
    {{ keyword }}
{% endfor %}
{% endmetablock %}
{% endif %}
{% endspaceless %}{% endblock meta_keywords %}{% endcomment %}


{% block main %}

{% block video_page_description %}
{% if page.get_absolute_url == request.path %}
{% editable page.richtextpage.content %}
{{ page.richtextpage.content|richtext_filter|safe }}
{% endeditable %}
{% endif %}
{% endblock video_page_description %}

<div class="loading">
    <img src="{{ STATIC_URL }}img/ajax-loader.gif" alt="loading icon" />
</div>

{% include "videos/list_display.html" %}
{% endblock main %}

{% block right_panel %}
    <!-- Video Categories -->
    <div class="title-divider">
	<h3>Categories</h3>
	<div class="divider-arrow"></div>
    </div>

    <section id="block-video-categories" class="post-widget block-grey">
	<ul class="clearfix block-light wrap15">
	    {% for category in category_list %}
	    <li>
		<a href="{% url "videos_category" category.slug %}">
		    {{ category.title }}
		</a>
	    </li>
	    {% endfor %}
	</ul>
    </section>
{% endblock %}

videos/templates/videos/blip_embed.html
<div id="video_embed">
    <script type="text/javascript">
        function getUpdate (changeType, param1, params2) {
            switch (changeType) {
                case "playlist_complete": 
                    check_playlist ();
                    break;
            }
        }
    </script>
    <object data="http://blip.tv/scripts/flash/stratos.swf" width="560" height="450" type="application/x-shockwave-flash" id="embed_player">
        <param name="movie" value="http://blip.tv/scripts/flash/stratos.swf" />
	    <param name="allowscriptaccess" value="always"/>
	    <param name="allowfullscreen" value="true"/>
	    <param name="flashvars" value="autostart=true&amp;enablejs=true&brandname=Need New Brand&amp;file={{ alias }}&amp;brandlink=http://www.ryochan7.com/" />
    </object>
</div>

videos/templates/videos/category.html
{% extends "videos/base.html" %}
{% load mezzanine_tags i18n %}

{% block meta_title %}Category: {{ category.title }}{% endblock meta_title %}
{% block title %}Category: {{ category.title }}{% endblock %}

{% block extra_js %}
<script type="text/javascript">
var popped = ('state' in window.history && window.history.state !== null);
var initialURL = location.href;

function list_paginate () {
    $(".pagination a").click (function (e) {
        e.preventDefault ();
        page_loaded = true;
        $("#page-content div.loading").show ();
        var block = $("#page-content #video_list_container");
        block.hide ();
        var scroll_offset = $("body").offset().top;
        $("html, body").animate({scrollTop:scroll_offset}, 200);
        var link_save = this.href;
        var sep = (link_save.indexOf("?")===-1)?"?":"&";
        var link_href = link_save + sep + "ajax=true";
        $.get (link_href, function (data) {
            $("#page-content div.loading").hide ();
            block.replaceWith (data);
            history.pushState(null, null, link_save);
            popped = true;
            list_paginate ();
        }).error (function () {
            alert ("Could not complete request");
        });
    });
}

$(document).ready (list_paginate);

$(window).bind('popstate', function() {
    var initialPop = (!popped && (location.href == initialURL));
    popped = true;
    if (!initialPop)
    {
        $("#page-content div.loading").show ();
        var block = $("#page-content #video_list_container");
        block.hide ();
        var scroll_offset = $("body").offset().top
        $("html, body").animate({scrollTop:scroll_offset}, 200);
        $.get (document.location, function (data) {
            $("#page-content div.loading").hide ();
            block.replaceWith (data);
            list_paginate ();
        }).error (function () {
            alert ("Could not complete request");
        });
    }
});

</script>
{% endblock extra_js %}

{% block breadcrumb_menu %}
{{ block.super }}
{% if page.get_absolute_url != category.get_absolute_url %}
  <li class="active">{{ category.title }}</li>
{% endif %}
{% endblock breadcrumb_menu %}


{% block video_page_description %}
{% if page.get_absolute_url == request.path %}
    {{ block.super }}
{% else %}
    {% editable category.summary %}
    {{ category.summary }}
    {% endeditable %}
{% endif %}
{% endblock video_page_description %}

videos/templates/videos/category_include.html
{% load mezzanine_tags i18n %}

 <!-- Video Categories -->
    <div class="title-divider">
	<h3>Categories</h3>
	<div class="divider-arrow"></div>
    </div>

    <section id="block-video-categories" class="post-widget block-grey">
	<ul class="clearfix block-light wrap15">
	    {% for category in category_list %}
	    <li>
		<a href="{% url "videos_category" category.slug %}">
		    {{ category.title }}
		</a>
	    </li>
	    {% endfor %}
	</ul>
    </section> 

videos/templates/videos/detail.html
{% extends "videos/base.html" %}
{% load mezzanine_tags pages_tags keyword_tags videos_tags comment_tags %}

{% block extra_xmlns %} xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml"{% endblock %}

{% block meta_title %}Video: {{ video.meta_title }}{% endblock meta_title %}

{% block meta_keywords %}
{% keywords_for video as tags %}

{% block meta_keywords_inner %}
{{ block.super }}
{% endblock meta_keywords_inner %}

{% endblock meta_keywords %}

{% block meta_description %}
{{ video.description }}
{% endblock meta_description %}

{% block extra_head %}
    <meta property="og:title" content="{{ video.title }}" />
    <meta property="og:type" content="video" />
    <meta property="og:url" content="http://{{ request.get_host }}{{ video.get_absolute_url }}" />
    {% if video.featured_image %}
        <meta property="og:image" content="{{ MEDIA_URL }}{{ video.featured_image }}" />
    {% else %}
        <meta property="og:image" content="{{ STATIC_URL }}img/default_video.png" />
    {% endif %}
    
    {% if video.meta_embed_url %}
	<meta property="og:video" content="{{ video.meta_embed_url }}" />
	<meta property="og:video:width" content="640" />
	<meta property="og:video:height" content="360" />
    {% endif %}
    
    <meta property="og:site_name" content="{{ settings.SITE_TITLE }}" />
    <meta property="fb:admins" content="738212647" />
    <meta property="og:description" content="{{ video.description }}" />
{% endblock extra_head %}

{% block extra_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{{ STATIC_URL }}asylum_theme/css/bootstrap-switch.css"  type="text/css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}asylum_theme/css/flat-ui-fonts.css"  type="text/css" />
{% endblock extra_css %}

{% block extra_js %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery_cookie/jquery.cookie.js"></script>
{% endblock extra_js %}

{% block breadcrumb_menu %}
{{ block.super }}
<li><a href="{% url "videos_category" video.category.slug %}">{{ video.category.title }}</a></li>
<li class="active">{{ video.title }}</li>
{% endblock breadcrumb_menu %}

{% block title %}
{% editable video.title %}
{{ video.title }}
{% endeditable %}
{% endblock title %}


{% block main %}
        <div id="video_detail">
            {% editable video.video_url %}
            <div class="video">
                {{ video.embed_code }}
            </div>
            {% endeditable %}

            <div id="video_info" class="block-dark wrap15">
		<div class="row">
		    <div class="span3">
			<p class="pub_date">Date: {{ video.publish_date|date:"N d, Y" }}</p>
			<p class="category">Category: <a href="{% url "videos_category" video.category.slug %}">{{ video.category.title }}</a></p>
                
			<a href="#" id="description_link" class="hide">Show Description</a>

			<div id="description">
			    {% editable video.content %}
			    {{ video.content|richtext_filter|safe }}
			    {% endeditable %}
			</div>
		    </div>

		    <div class="span3 offset1">
			<p class="origin">
			    Origin URL: <br/>
			    <input type="text" value="{{ video.video_url }}" />
			</p>

			<div id="video_options">
			    <form method="post" action="">
				{% csrf_token %}
				<div>
				    <label for="{{ video_options.autoplay.html_name }}">{{ video_options.autoplay.label }}:</label>
				    <div id="autoplay-switch" class="make-switch" data-on="on" data-off="off">
				        {{ video_options.autoplay }}
				    </div>
				</div>
			    </form>
			</div>
		    </div>
		</div>

		<div class="row">

		<div class="span7">
		    <h3>Share This:</h3>
		    <!-- AddThis Button BEGIN -->
		    <div class="addthis_toolbox addthis_default_style addthis_32x32_style">
		    <a class="addthis_button_preferred_1"></a>
		    <a class="addthis_button_preferred_2"></a>
		    <a class="addthis_button_preferred_3"></a>
		    <a class="addthis_button_preferred_4"></a>
		    <a class="addthis_button_compact"></a>
		    <a class="addthis_counter addthis_bubble_style"></a>
		    </div>
		    <!-- AddThis Button END -->
		    </div>
		</div>
            </div>
        </div>
{% endblock main %}


{% block left_panel %}
    <div class="row">
	<div class="span8">
	    {% block title_wrapper %}{{ block.super }}{% endblock %}
	    {% block main_wrapper %}{{ block.super }}{% endblock %}
	</div>
    </div>

    {% if video.allow_comments %}
	<div class="row">
	    <div class="span8">
		{% comments_for video %}
	    </div>
	</div>
    {% endif %}
{% endblock left_panel %}

{% block right_panel %}
    <div class="title-divider">
	<h3>Related Videos</h3>
	<div class="divider-arrow"></div>
    </div>

    <section id="adjacent_videos" class="block-grey">
	<div class="block-light wrap15">
	    {% adjacent_videos video %}
	</div>
    </section>

    {% video_categories_block %}
{% endblock right_panel %}

{% block extra_footer %}
<script type="text/javascript">
    $(document).ready (function () {
	var block = $("div#video_info #description");

	// Hide description div and show description_link
	$("div#video_info a#description_link").show ();
	block.toggleClass ("hide");

	// Set onclick function
	$("div#video_info a#description_link").click (function (e) {
	    e.preventDefault();
	    var block = $("div#video_info #description");
	    if (block.hasClass ("hide")) {
		// Display will become visible.
		$(this).text ("Hide Description");
		block.slideToggle("slow");
	    }
	    else {
		// Display will become hidden.
		$(this).text ("Show Description");
		block.slideToggle("slow");
	    }

	    block.toggleClass ("hide");
	});
	$("#video_options input#id_autoplay").click (function () {
	    if ($(this).attr ("checked")) {
		$.cookie ("autoplay", "true", {path: "/"});
	    }
	    else {
		$.cookie ("autoplay", null, {path: "/"});
	    }
	});
    });
</script>

<script type="text/javascript">
    function check_playlist () {
	{% if previous_video %}
	if ($.cookie ("autoplay")) {
	    window.location.href = "{{ previous_video.get_absolute_url }}";
	}
	{% endif %}
    }

    function adjacent_paginate () {
	$("#video-list-container a.paginate").click (function (e) {
	    e.preventDefault ();
	    $("#video-list-container div.loading").show ();
	    var list_block = $("#video-list-container ul");
	    var parent_block = $("#video-list-container");
	    list_block.hide ();
	    $.get (this.href, function (data) {
		$("#video-list-container div.loading").hide ();
		parent_block.replaceWith (data);
		adjacent_paginate ();
	    }).error (function () {
		alert ("Could not complete request");
	    });
	});
    }
    $(document).ready (adjacent_paginate);
    
    $("#video_options #autoplay-switch").on("switch-change", function(e, data) {       
        if (data.value == true) {
            $("#video_options input#id_autoplay").attr("checked", "checked");
	    $.cookie ("autoplay", "true", {path: "/"});
	}
	else {
	    $("#video_options input#id_autoplay").removeAttr("checked");
	    $.cookie ("autoplay", null, {path: "/"});
	}
    });
</script>

<script type="text/javascript">
    var addthis_config = {"data_track_clickback":true};
</script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4e2e83b10c45efee">
</script>

<script type="text/javascript" src="{{ STATIC_URL }}asylum_theme/js/bootstrap-switch.min.js"></script>

{% endblock extra_footer %}

videos/templates/videos/featured.html
{% load mezzanine_tags %}
    <ul class="slides">
        {% for video in latest_video_list %}
        <li>
            <a href="{{ video.get_absolute_url }}" title="{{ video.title }}">
                {% if video.featured_image %}
                    <img src="{{ MEDIA_URL }}{% thumbnail video.featured_image 768 409 %}" alt="{{ video.title }}" />
                {% else %}
                    <img src="{{ STATIC_URL }}img/default_video_120x90.png" alt="{{ video.title }}" />
                {% endif %}
	    </a>

	    <a href="{{ video.get_absolute_url }}" title="{{ video.title }}">
		<h3><span>{{ video.title }}</span>{{ video.description }}</h3>
            </a>
        </li>
        {% endfor %}
    </ul>

videos/templates/videos/list_display.html
{% load mezzanine_tags i18n asylum_tags %}
<div id="video_list_container">
    <ul id="video_list" class="clearfix">
    {% for video in video_list %}
        <li class="video_panel">
	    <div class="row">
		<a href="{{ video.get_absolute_url }}">
		    <div class="span3 video_list_left_panel">
			<img src="{{ MEDIA_URL }}{% thumbnail video.featured_image 270 149 %}" alt="{{ video.title }}" />
			<div class="pub_date">
			    <span>{{ video.publish_date|date:"m/d/Y" }}</span>
			</div>
		    </div>
		    <div class="summary_info span4">
			<h4>{{ video.title }}</h4>
			<p class="summary">
			    {{ video.description }}
			</p>
		    </div>
		</a>
	    </div>
        </li>
    {% endfor %}
    </ul>
    {% custom_pagination_for page_obj %}
</div>